version: '3.9'

services:
  app:
    build:
      context: ./docker/django
    command: >
      sh -c " set -e && 

              until nc -z db 5432; do
                  echo 'Aguardando Banco de Dados...'
                  sleep 2s
              done &&
              echo 'Banco de Dados Pronto!' &&

              python manage.py collectstatic --noinput &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    depends_on: 
      - db
    environment:
      - DJANGO_SECRET_KEY=devsecretkey
      - DJANGO_DEBUG=1
      - DJANGO_ALLOWED_HOSTS=127.0.0.1
      - DB_HOST=db
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=dbuserpass
    volumes:
      - ./data/web:/vol/web
      - ./docker/django/app:/app
    ports:
      - 8000:8000
    networks:
      - django_net

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbuserpass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - django_net
  
networks:
  django_net:
    driver: bridge

volumes:
  postgres-data: